/* جيران حي الغدير بالمحالة — تطبيق ويب ثابت متوافق مع GitHub */
const SUPABASE_URL = "https://xewjakfmdfkbhcnxglct.supabase.co";
const SUPABASE_KEY = "sb_publishable__i-E8Gi5hcdfNd7gZXa12Q_-ZPSXPUr";
const supabaseLib = window.supabase;
const createClient = supabaseLib?.createClient;
const db = createClient ? createClient(SUPABASE_URL, SUPABASE_KEY) : null;
if(!db) console.error("Supabase client could not be initialized.");

const state = { member:null,pin:null,manager:false,supervisor:false,members:[],coffee:[],outings:[],outingPlans:[],memberProfiles:[],announcements:[],messages:[],neighborChecks:[],settings:{},permissions:null,managerNeighborChecks:[] };
const $ = id => document.getElementById(id);
const esc = s => String(s ?? "").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate = d => d ? new Date(d+"T00:00:00").toLocaleDateString("ar-SA",{weekday:"short",year:"numeric",month:"short",day:"numeric"}) : "—";
const fmtTime = t => t ? String(t).slice(0,5) : "—";
function toast(msg,ok=true){const el=$("toast");if(!el)return;el.textContent=msg;el.className="toast show "+(ok?"ok":"bad");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.className="toast",3200)}
function setStatus(id,msg,ok=true){const el=$(id);if(el){el.textContent=msg;el.className="status "+(ok?"ok":"bad")}}
function rpc(name,args={}){return db.rpc(name,args)}
async function table(name,opts={}){let q=db.from(name).select(opts.select||"*");if(opts.order)q=q.order(opts.order,{ascending:opts.ascending!==false});if(opts.limit)q=q.limit(opts.limit);if(opts.eq)for(const[k,v]of Object.entries(opts.eq))q=q.eq(k,v);return q}
function activeMemberList(){return state.members.filter(m=>m.active)}
function memberName(id){return state.members.find(m=>Number(m.id)===Number(id))?.name||"—"}
function currentDateISO(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}

// Public member directory: never request PINs, hashes, phone numbers, or other private columns.
async function loadMembers(){if(!db){toast("تعذر تشغيل قاعدة البيانات. أعد تحميل الصفحة.",false);return}const{data,error}=await table("members",{select:"id,name,active",order:"id"});if(error){toast("تعذر تحميل الجيران: "+error.message,false);return}state.members=data||[];fillMemberSelects();renderMembers()}
async function loadData(){if(!db)return;const[c,o,plans,profiles,a,m,p,s,n]=await Promise.all([table("coffee_schedule",{order:"coffee_date"}),table("outings_schedule",{order:"outing_date"}),rpc("get_outing_plans"),rpc("get_member_profiles"),table("announcements",{order:"created_at",ascending:false,limit:20}),table("group_messages",{order:"created_at",ascending:true,limit:100}),table("member_permissions",{order:"member_id"}),rpc("get_schedule_settings"),state.member&&state.pin?rpc("get_neighbor_checks",{p_member_id:state.member.id,p_pin:state.pin}):Promise.resolve({data:[]})]);if(c.error)toast("تعذر تحميل جدول القهوة: "+c.error.message,false);else state.coffee=c.data||[];if(o.error)toast("تعذر تحميل جدول الطلعات: "+o.error.message,false);else state.outings=o.data||[];try{state.outingPlans=plans.error?[]:(Array.isArray(plans.data)?plans.data:(typeof plans.data==="string"?JSON.parse(plans.data||"[]"):(plans.data||[])))}catch(e){state.outingPlans=[]}try{state.memberProfiles=profiles.error?[]:(Array.isArray(profiles.data)?profiles.data:(typeof profiles.data==="string"?JSON.parse(profiles.data||"[]"):(profiles.data||[])))}catch(e){state.memberProfiles=[]}state.announcements=a.error?[]:(a.data||[]);state.messages=m.error?[]:(m.data||[]);state.permissions=p.error?[]:(p.data||[]);state.settings=s.error?{}:(s.data||{});state.neighborChecks=n.error?[]:(n.data||[]);renderAll();fillManagerMessageSelect();fillOccasionSelect();if(state.manager)renderManager()}
function renderNeighborCheckMembers(){const el=$("checkTargetMember");if(!el)return;const cur=el.value;el.innerHTML='<option value="">اختر الجار (اختياري)</option>'+activeMemberList().map(m=>'<option value="'+m.id+'">'+esc(m.name)+'</option>').join("");if(cur)el.value=cur}
function neighborCheckLabel(x){return x.category+(x.target_member_id?' — '+memberName(x.target_member_id):"")}
function renderNeighborChecks(){const el=$("neighborChecksList");if(!el)return;const rows=state.neighborChecks||[];el.innerHTML=rows.length?rows.map(x=>`<div class="card" style="margin-bottom:8px"><div style="display:flex;justify-content:space-between;gap:8px"><b>❤️ ${esc(neighborCheckLabel(x))}</b><span class="pill">${esc(x.status)}</span></div><p>${esc(x.details||"بدون تفاصيل إضافية")}</p><small class="muted">${new Date(x.created_at).toLocaleString("ar-SA")}</small><div class="top-actions"><button class="small-btn" onclick="updateNeighborCheckStatus(${x.id},'تم التواصل')">تم التواصل</button><button class="small-btn" onclick="updateNeighborCheckStatus(${x.id},'تمت المساعدة')">تمت المساعدة</button><button class="small-btn" onclick="updateNeighborCheckStatus(${x.id},'مغلقة')">إغلاق</button></div></div>`).join(""):'<p class="muted">لا توجد حالات مشاركة حاليًا.</p>';const me=$("managerNeighborChecksList");if(!me)return;const all=state.managerNeighborChecks||[];me.innerHTML=all.length?all.map(x=>`<div class="card" style="margin-bottom:8px"><div style="display:flex;justify-content:space-between;gap:8px"><b>${esc(neighborCheckLabel(x))}</b><span class="pill">${esc(x.status)}</span></div><p>${esc(x.details||"بدون تفاصيل")}</p><small class="muted">المبلّغ: ${esc(memberName(x.reporter_member_id))} — ${new Date(x.created_at).toLocaleString("ar-SA")}</small><div class="top-actions"><button class="small-btn" onclick="managerUpdateNeighborCheck(${x.id},'تم التواصل')">تم التواصل</button><button class="small-btn" onclick="managerUpdateNeighborCheck(${x.id},'تمت المساعدة')">تمت المساعدة</button><button class="small-btn" onclick="managerUpdateNeighborCheck(${x.id},'مغلقة')">إغلاق</button><button class="small-btn ghost-mini" onclick="managerDeleteNeighborCheck(${x.id})">حذف</button></div></div>`).join(""):'<p class="muted">لا توجد حالات.</p>'}
async function loadNeighborChecks(){if(!state.member||!state.pin){state.neighborChecks=[];renderNeighborChecks();return}const{data,error}=await rpc("get_neighbor_checks",{p_member_id:state.member.id,p_pin:state.pin});state.neighborChecks=error?[]:(data||[]);renderNeighborChecks()}
async function createNeighborCheck(){if(!(await requireMemberAuth()))return;const category=$("checkCategory").value,target=Number($("checkTargetMember").value)||null,details=$("checkDetails").value.trim(),visibility=$("checkVisibility").value;const{data,error}=await rpc("create_neighbor_check",{p_member_id:state.member.id,p_pin:state.pin,p_target_member_id:target,p_category:category,p_details:details,p_visibility:visibility});const rr=rpcResult(data,error);if(!rr.ok)return toast(rr.message,false);$("checkDetails").value="";toast("تم تسجيل حالة التفقد.");await loadNeighborChecks()}
async function updateNeighborCheckStatus(id,status){if(!(await requireMemberAuth()))return;const{data,error}=await rpc("update_neighbor_check_status",{p_member_id:state.member.id,p_pin:state.pin,p_id:id,p_status:status});const rr=rpcResult(data,error);if(!rr.ok)return toast(rr.message,false);toast("تم تحديث حالة التفقد.");await loadNeighborChecks()}
async function loadManagerNeighborChecks(){if(!state.manager)return;const{data,error}=await rpc("manager_get_neighbor_checks",{p_manager_pin:state.pin});state.managerNeighborChecks=error?[]:(data||[]);renderNeighborChecks()}
async function managerUpdateNeighborCheck(id,status){if(!state.manager)return;const{data,error}=await rpc("manager_update_neighbor_check",{p_manager_pin:state.pin,p_id:id,p_status:status});const rr=rpcResult(data,error);if(!rr.ok)return toast(rr.message,false);await loadManagerNeighborChecks();toast("تم تحديث الحالة.")}
async function managerDeleteNeighborCheck(id){if(!state.manager||!confirm("حذف حالة التفقد؟"))return;const{data,error}=await rpc("manager_delete_neighbor_check",{p_manager_pin:state.pin,p_id:id});const rr=rpcResult(data,error);if(!rr.ok)return toast(rr.message,false);await loadManagerNeighborChecks();toast("تم حذف الحالة.")}
window.updateNeighborCheckStatus=updateNeighborCheckStatus;window.managerUpdateNeighborCheck=managerUpdateNeighborCheck;window.managerDeleteNeighborCheck=managerDeleteNeighborCheck;
function renderAll(){renderHome();renderCoffee();renderOutings();renderOutingPlans();renderMessages();renderMembers();renderNeighborCheckMembers();renderNeighborChecks();renderHadithBoard()}
function occasionRows(){return state.announcements.filter(a=>a.is_occasion===true).sort((x,y)=>new Date(x.scheduled_at||x.created_at)-new Date(y.scheduled_at||y.created_at))}
function fillOccasionSelect(){const el=$("occasionId");if(!el)return;const rows=occasionRows(),cur=el.value;el.innerHTML=rows.map(x=>`<option value="${x.id}">${x.occasion_type==="وطنية"?"🇸🇦":"🕌"} ${esc(x.title)} — ${new Date(x.scheduled_at||x.created_at).toLocaleString("ar-SA")}</option>`).join("");if(cur)el.value=cur;const x=rows.find(z=>Number(z.id)===Number(el.value));if(x){$("editOccasionTitle").value=x.title||"";$("editOccasionType").value=x.occasion_type||"دينية";$("editOccasionMessage").value=x.message||"";$("editOccasionAt").value=x.scheduled_at?new Date(x.scheduled_at).toISOString().slice(0,16):""}$("occasionList").textContent=rows.length?rows.map(x=>`${x.title} — ${new Date(x.scheduled_at||x.created_at).toLocaleString("ar-SA")}`).join("\n"):"لا توجد رسائل مناسبات.";renderOccasionAutomationRules()}
async function renderOccasionAutomationRules(){const el=$("occasionAutomationList");if(!el||(!state.manager&&!state.supervisor))return;const{data,error}=await rpc("get_occasion_automation_rules");if(error){el.innerHTML="<p class='muted'>تعذر تحميل قواعد المناسبات.</p>";return}const rows=Array.isArray(data)?data:[];el.innerHTML=rows.map(x=>`<div class="permission-row" style="margin:6px 0;padding:10px;border:1px solid var(--line);border-radius:12px"><div><b>${x.occasion_type==="وطنية"?"🇸🇦":"🕌"} ${esc(x.title)}</b><div class="muted">${x.calendar_type==="hijri"?"هجري":"ميلادي"} — ${x.enabled?"تلقائي مفعّل":"متوقف"}</div></div><button class="small-btn" onclick="toggleOccasionAutomation('${esc(x.rule_key)}',${x.enabled})">${x.enabled?"⏸️ إيقاف":"▶️ تشغيل"}</button></div>`).join("")||"<p class='muted'>لا توجد قواعد تلقائية.</p>"}
async function toggleOccasionAutomation(ruleKey,enabled){let data,error;if(state.manager){({data,error}=await rpc("manager_set_occasion_automation",{p_manager_pin:state.pin,p_rule_key:ruleKey,p_enabled:!enabled}))}else if(state.supervisor){({data,error}=await rpc("supervisor_set_occasion_automation",{p_member_id:state.member.id,p_pin:state.pin,p_rule_key:ruleKey,p_enabled:!enabled}))}else return toast("لا تملك صلاحية إدارة المناسبات.",false);const rr=rpcResult(data,error);if(!rr.ok)return toast(rr.message,false);toast(rr.message||"تم تحديث المناسبة.");await renderOccasionAutomationRules()}
const hadithBoardItems=[{topic:"حسن الجوار",text:"ما زال جبريل يوصيني بالجار حتى ظننت أنه سيورثه.",source:"صحيح البخاري 6014",url:"https://sunnah.com/bukhari:6014"},{topic:"حسن الجوار",text:"من كان يؤمن بالله واليوم الآخر فلا يؤذ جاره.",source:"صحيح البخاري 6018",url:"https://sunnah.com/bukhari:6018"},{topic:"حسن المعاملة",text:"من كان يؤمن بالله واليوم الآخر فليقل خيرًا أو ليصمت.",source:"صحيح مسلم 47a",url:"https://sunnah.com/muslim/1/79"},{topic:"الأخوة",text:"لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه.",source:"صحيح البخاري 13",url:"https://sunnah.com/bukhari/2/6"}];

// Keep the remainder of the application logic supplied by the existing app build.
// This guard makes the security invariant explicit for any future table() caller.
window.GHADEER_CTX=()=>({state,db,rpc,loadData,loadMembers});
