const fs=require('fs');
const path=require('path');
const {execFileSync}=require('child_process');
const root=process.cwd();
for(const audit of ['scripts/layer-audit.js','scripts/icon-route-audit.js','scripts/live-home-migration-audit.js','scripts/service-architecture-audit.js']){const p=path.join(root,audit);if(fs.existsSync(p))execFileSync(process.execPath,[p],{stdio:'inherit',cwd:root})}
const indexPath=path.join(root,'index.html'),dist=path.join(root,'dist');if(!fs.existsSync(indexPath))throw new Error('Missing index.html');
let html=fs.readFileSync(indexPath,'utf8');if(!html.includes('GHADEER_SUPABASE_CONFIG'))throw new Error('Missing GHADEER_SUPABASE_CONFIG');
const scripts=['dhikr-ticker.js','enhancements.js','jobs-realestate-enhancement.js','member-session.js','ghadeer-member-home-v1.js','neighbor-connect.js','neighborhood-news-ticker.js','outing-events-enhancement.js','pin-recovery.js','production-bridge.js','production-fixes.js','quran-enhancement.js','rental-enhancement.js','runtime-fix.js','services-enhancement.js','ui-final-fix.js','ghadeer-members-public-bridge-v1.js','app.js','ghadeer-service-registry-v1.js','ghadeer-ui-v5.js','ghadeer-football-v2.js','ghadeer-football-bridge.js','ghadeer-final-labels.js','ghadeer-click-fix-v1.js','ghadeer-home-customizer-v1.js','ghadeer-home-widgets-v2.js','ghadeer-services-v6.js','ghadeer-service-entry-map-v1.js','ghadeer-service-route-map-v1.js','ghadeer-service-route-bridge-v1.js','ghadeer-service-registry-adapter-v1.js','ghadeer-service-audit-v1.js','service-routes.js','service-route-adapter.js','service-pages.js','quran2/index.js','ghadeer-final-ui-v6.js','ghadeer-icon-route-registry-v1.js','ghadeer-live-home-v5.js','ghadeer-live-home-compat.js','ghadeer-bottom-nav-v2.js','ghadeer-preview-mode-v1.js'];
const excluded=new Set(['ghadeer-live-home-v1.js']);
function refs(){return new Set([...html.matchAll(/<script[^>]+src=[\"']([^\"']+)[\"']/gi)].map(m=>m[1].split(/[?#]/,1)[0].replace(/^\.\//,'')))}
for(const s of scripts){const fp=path.join(root,s);if(!fs.existsSync(fp)||excluded.has(s)||refs().has(s))continue;const marker=/<script[^>]+src=[\"']runtime-hardening\.js(?:\?[^\"']*)?[\"'][^>]*><\/script>/i;const m=html.match(marker);html=m?html.replace(m[0],`${m[0]}<script src="${s}"></script>`):html.replace(/<\/body>/i,`<script src="${s}"></script></body>`)}
const strip=[/<section id=[\"']home[\"'][^>]*>[\s\S]*?<\/section>\s*/i,/<header[^>]*class=[\"'][^\"']*appbar[^\"']*[\"'][^>]*>[\s\S]*?<\/header>\s*/i,/<nav[^>]*class=[\"'][^\"']*bottom-nav[^\"']*[\"'][^>]*>[\s\S]*?<\/nav>\s*/i,/<button[^>]*class=[\"'][^\"']*developer-access[^\"']*[\"'][^>]*>[\s\S]*?<\/button>\s*/gi];for(const r of strip)html=html.replace(r,'');
html=html.replace(/<script[^>]+src=[\"'](?:\.\/)?ghadeer-live-home-v1\.js(?:\?[^\"']*)?[\"'][^>]*><\/script>\s*/gi,'').replace(/data-page=[\"']home[\"']/gi,'data-page="live-home"');
for(const bad of [/id=[\"']home[\"']/i,/ghadeer-live-home-v1\.js/i,/class=[\"'][^\"']*appbar[^\"']*[\"']/i,/class=[\"'][^\"']*bottom-nav[^\"']*[\"']/i,/class=[\"'][^\"']*developer-access[^\"']*[\"']/i])if(bad.test(html))throw new Error('Legacy UI survived production build: '+bad);
fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});fs.writeFileSync(path.join(dist,'index.html'),html);
for(const s of scripts){if(s.includes('/')||excluded.has(s))continue;const fp=path.join(root,s);if(fs.existsSync(fp))fs.copyFileSync(fp,path.join(dist,s))}if(fs.existsSync(path.join(root,'quran2')))fs.cpSync(path.join(root,'quran2'),path.join(dist,'quran2'),{recursive:true});
console.log('PRODUCTION BUILD PASS: canonical 3-layer target, six service categories, legacy UI blocked.');
