const fs=require('fs');
const path=require('path');
const root=process.cwd();
const indexPath=path.join(root,'index.html');
const dist=path.join(root,'dist');
if(!fs.existsSync(indexPath))throw new Error('Missing index.html');
let deployIndex=fs.readFileSync(indexPath,'utf8');
if(!deployIndex.includes('GHADEER_SUPABASE_CONFIG'))throw new Error('Missing GHADEER_SUPABASE_CONFIG in index.html');
// Canonical pipeline. Release-critical audit/gate scripts are REQUIRED: silently skipping them is a build failure.
const featureScripts=['ghadeer-service-registry-v1.js','ghadeer-ui-v5.js','ghadeer-quran-v5.js','ghadeer-football-v1.js','ghadeer-football-v2.js','ghadeer-football-bridge.js','ghadeer-final-labels.js','ghadeer-click-fix-v1.js','ghadeer-home-customizer-v1.js','ghadeer-home-widgets-v2.js','ghadeer-navigation-fix-v1.js','ghadeer-services-v6.js','ghadeer-service-route-map-v1.js','ghadeer-service-route-bridge-v2.js','ghadeer-service-registry-adapter-v1.js','ghadeer-service-manifest-v1.js','ghadeer-service-ownership-v1.js','ghadeer-service-contract-v2.js','ghadeer-service-navigation-v1.js','ghadeer-ui-service-contract-v1.js','ghadeer-service-ui-migration-audit-v1.js','ghadeer-service-action-map-v1.js','ghadeer-service-action-classifier-v1.js','ghadeer-service-dedup-policy-v1.js','ghadeer-service-dedup-decisions-v1.js','ghadeer-service-integration-audit-v1.js','ghadeer-service-backend-integration-audit-v1.js','ghadeer-service-backend-contract-v1.js','ghadeer-service-isolation-audit-v1.js','ghadeer-service-shared-dependency-audit-v1.js','ghadeer-service-file-dependency-audit-v1.js','ghadeer-service-function-dependency-audit-v1.js','ghadeer-service-event-dependency-audit-v1.js','ghadeer-service-async-dependency-audit-v1.js','ghadeer-service-dependency-risk-matrix-v1.js','ghadeer-service-refactor-plan-v1.js','ghadeer-service-boundary-v1.js','ghadeer-service-public-api-v1.js','ghadeer-service-public-api-audit-v1.js','ghadeer-service-backend-api-audit-v1.js','ghadeer-service-route-api-audit-v1.js','ghadeer-service-ui-route-audit-v1.js','ghadeer-service-ui-action-audit-v1.js','ghadeer-service-action-backend-audit-v1.js','ghadeer-service-execution-map-v1.js','ghadeer-service-execution-readiness-v1.js','ghadeer-service-preflight-v1.js','ghadeer-service-before-after-rollback-v1.js','ghadeer-service-refactor-transaction-gate-v1.js','ghadeer-service-gate-selftest-v1.js','ghadeer-service-gate-negative-tests-v1.js','ghadeer-service-candidate-selection-v1.js','ghadeer-service-candidate-certification-v1.js','ghadeer-service-candidate-certification-selftest-v1.js','ghadeer-ui-integrity-audit-v1.js','ghadeer-ui-release-gate-v1.js','ghadeer-service-ui-navigation-v1.js','ghadeer-service-audit-v2.js'];
const requiredReleaseGates=['ghadeer-service-gate-selftest-v1.js','ghadeer-service-gate-negative-tests-v1.js','ghadeer-service-candidate-certification-selftest-v1.js','ghadeer-ui-integrity-audit-v1.js','ghadeer-ui-release-gate-v1.js'];
for(const script of requiredReleaseGates){if(!fs.existsSync(path.join(root,script)))throw new Error(`Missing required release gate: ${script}`);}
function injectIfPresent(scriptName){const filePath=path.join(root,scriptName);if(!fs.existsSync(filePath)||deployIndex.includes(`src="${scriptName}"`))return;const marker=/<script[^>]+src=["']runtime-hardening\.js(?:\?[^"']*)?["'][^>]*><\/script>/i;const match=deployIndex.match(marker);if(match)deployIndex=deployIndex.replace(match[0],`${match[0]}<script src="${scriptName}"></script>`);else deployIndex=deployIndex.replace(/<\/body>/i,`<script src="${scriptName}"></script></body>`)}
for(const script of featureScripts)injectIfPresent(script);
fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});fs.writeFileSync(path.join(dist,'index.html'),deployIndex,'utf8');
for(const entry of fs.readdirSync(root,{withFileTypes:true})){if(!entry.isFile())continue;if(entry.name==='build.js'||entry.name==='worker.js')continue;if(!/\.(?:js|css)$/i.test(entry.name)&&entry.name!=='_redirects')continue;fs.copyFileSync(path.join(root,entry.name),path.join(dist,entry.name));}
console.log(`Ghadeer production artifact generated successfully: ${dist}`);
