/* Ghadeer UI enhancements — sports, weather, prayer iqama/alerts, Quran source, neighborhood services */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const HOME='home';

  function injectStyle(){
    if($('ghadeerEnhStyle'))return;
    const s=document.createElement('style');s.id='ghadeerEnhStyle';s.textContent=`
      .gh-weather{display:flex;align-items:center;justify-content:space-between;gap:10px;border-radius:18px;padding:12px 14px;color:#fff;box-shadow:0 8px 22px #0002;margin:0 0 12px;cursor:pointer;transition:.25s}.gh-weather:hover{transform:translateY(-1px)}.gh-weather-temp{font-size:30px;font-weight:900}.gh-weather-meta{font-size:12px;opacity:.92}.gh-weather-icon{font-size:34px}.gh-weather-detail{font-size:12px;margin-top:4px}.gh-prayer{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin-top:10px}.gh-prayer .pbox{background:#f4faf6;border:1px solid #dcebe1;border-radius:12px;padding:8px;text-align:center}.gh-prayer .pbox b{font-size:17px}.gh-iqama{font-size:11px;color:#71695f;margin-top:3px}.gh-next-prayer{margin-top:9px;padding:9px 11px;border-radius:12px;background:#fff8df;border:1px solid #ead9a4;font-weight:800}.gh-sport-tabs{display:flex;gap:7px;overflow:auto;margin-bottom:10px}.gh-sport-tabs button{white-space:nowrap;border:1px solid #d8ccbb;background:#fff;border-radius:999px;padding:8px 12px}.gh-sport-tabs button.active{background:#176b45;color:#fff}.gh-match{display:grid;grid-template-columns:1fr auto 1fr;gap:8px;align-items:center;border:1px solid #e4dacb;border-radius:14px;padding:10px;margin:7px 0;background:#fff}.gh-team{text-align:center;font-weight:800}.gh-match-time{text-align:center;font-size:12px;color:#71695f}.gh-channel{font-size:11px;color:#176b45;text-align:center;margin-top:3px}.gh-news a{display:block;padding:9px 0;border-bottom:1px solid #eee4d5;text-decoration:none;color:#176b45}.gh-news a:last-child{border-bottom:0}.gh-service{display:flex;align-items:center;gap:10px}.gh-service .icon{font-size:25px}.gh-temp-cold{background:linear-gradient(135deg,#1767c8,#55b8ff)}.gh-temp-mild{background:linear-gradient(135deg,#1f8f72,#7fcf67)}.gh-temp-warm{background:linear-gradient(135deg,#d79b22,#ef6c2f)}.gh-temp-hot{background:linear-gradient(135deg,#d52b2b,#8d1515)}@media(max-width:650px){.gh-prayer{grid-template-columns:repeat(2,1fr)}.gh-match{grid-template-columns:1fr}.gh-match-time{order:-1}.gh-channel{margin-bottom:3px}}
    `;document.head.appendChild(s);
  }

  function weatherClass(t){if(t<=12)return'gh-temp-cold';if(t<=25)return'gh-temp-mild';if(t<=35)return'gh-temp-warm';return'gh-temp-hot';}
  function weatherIcon(code){if(code===0)return'☀️';if(code<=3)return'🌤️';if(code<=48)return'🌫️';if(code<=67)return'🌧️';if(code<=77)return'🌨️';if(code<=82)return'🌦️';return'⛈️';}
  let lastWeather=null;
  async function getLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('geolocation'));navigator.geolocation.getCurrentPosition(p=>resolve(p.coords),reject,{enableHighAccuracy:false,timeout:12000,maximumAge:300000});});}
  async function loadWeather(){
    const box=$('ghWeatherBox');if(!box)return;
    box.innerHTML='<div><b>🌡️ الطقس</b><div class="gh-weather-meta">جارٍ تحديث موقعك والطقس…</div></div><div class="gh-weather-icon">⏳</div>';
    try{const c=await getLocation();const u='https://api.open-meteo.com/v1/forecast?latitude='+encodeURIComponent(c.latitude)+'&longitude='+encodeURIComponent(c.longitude)+'&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto';const j=await fetch(u,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('weather '+r.status);return r.json()});const w=j.current;lastWeather={...w,lat:c.latitude,lon:c.longitude};box.className='gh-weather '+weatherClass(Number(w.temperature_2m));box.innerHTML='<div><div class="gh-weather-temp">'+Math.round(w.temperature_2m)+'°</div><div class="gh-weather-meta">الحرارة الحالية • المحسوسة '+Math.round(w.apparent_temperature)+'°</div><div class="gh-weather-detail">💧 '+Math.round(w.relative_humidity_2m)+'% • 💨 '+Math.round(w.wind_speed_10m)+' كم/س</div></div><div class="gh-weather-icon">'+weatherIcon(Number(w.weather_code))+'</div>';
      box.onclick=()=>showWeatherDetails();
    }catch(e){box.className='gh-weather gh-temp-mild';box.innerHTML='<div><b>🌡️ الطقس</b><div class="gh-weather-meta">تعذر تحديد الموقع. فعّل الموقع ثم اضغط للتحديث.</div></div><div class="gh-weather-icon">📍</div>';box.onclick=loadWeather;}
  }
  function showWeatherDetails(){
    if(!lastWeather)return loadWeather();
    alert('الطقس الآن\n\nدرجة الحرارة: '+Math.round(lastWeather.temperature_2m)+'°\nالمحسوسة: '+Math.round(lastWeather.apparent_temperature)+'°\nالرطوبة: '+Math.round(lastWeather.relative_humidity_2m)+'%\nالرياح: '+Math.round(lastWeather.wind_speed_10m)+' كم/س\n\nيتحدث تلقائيًا كل 10 دقائق.');
  }
  function mountWeather(){const home=$('home');if(!home||$('ghWeatherBox'))return;const hero=home.querySelector('.hero');if(!hero)return;const box=document.createElement('div');box.id='ghWeatherBox';box.className='gh-weather gh-temp-mild';hero.insertAdjacentElement('afterend',box);loadWeather();setInterval(loadWeather,600000);}

  function addPrayerUI(){
    const card=$('prayerTimesToday')?.parentElement;if(!card||$('ghPrayerExtra'))return;
    const x=document.createElement('div');x.id='ghPrayerExtra';x.innerHTML='<div class="gh-prayer"><div class="pbox">الفجر<br><b id="ghFajrA">—</b><div class="gh-iqama">الإقامة <span id="ghFajrI">—</span></div></div><div class="pbox">الظهر<br><b id="ghDhuhrA">—</b><div class="gh-iqama">الإقامة <span id="ghDhuhrI">—</span></div></div><div class="pbox">العصر<br><b id="ghAsrA">—</b><div class="gh-iqama">الإقامة <span id="ghAsrI">—</span></div></div><div class="pbox">المغرب<br><b id="ghMaghribA">—</b><div class="gh-iqama">الإقامة <span id="ghMaghribI">—</span></div></div><div class="pbox">العشاء<br><b id="ghIshaA">—</b><div class="gh-iqama">الإقامة <span id="ghIshaI">—</span></div></div></div><div id="ghNextPrayer" class="gh-next-prayer">اضغط «استخدام موقعي» لتحديث المواقيت والتنبيهات.</div><div class="top-actions"><button id="ghPrayerNotify" class="btn secondary">🔔 تنبيه الأذان والإقامة</button></div>';
    card.appendChild(x);$('ghPrayerNotify').onclick=enablePrayerNotifications;
  }
  function plusMinutes(hm,min){const [h,m]=String(hm).slice(0,5).split(':').map(Number);if(!Number.isFinite(h)||!Number.isFinite(m))return'—';const d=new Date();d.setHours(h,m+min,0,0);return d.toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit',hour12:false});}
  function prayerAlert(prayer,time,type){if(Notification.permission==='granted')new Notification('جيران حي الغدير',{body:(type==='adhan'?'حان أذان ':'حان وقت الإقامة ')+prayer+' — '+time});}
  async function enablePrayerNotifications(){if(!('Notification'in window))return alert('المتصفح لا يدعم تنبيهات النظام.');const p=await Notification.requestPermission();if(p==='granted'){localStorage.setItem('gh_prayer_notify','1');alert('تم تفعيل تنبيهات الأذان والإقامة.');checkPrayerAlerts();}else alert('لم يتم السماح بالتنبيهات.');}
  let prayerCache={};
  function checkPrayerAlerts(){const t=prayerCache;const now=new Date();const mins=now.getHours()*60+now.getMinutes();for(const [name,time] of Object.entries(t)){if(!time||time==='—')continue;const [h,m]=time.split(':').map(Number),base=h*60+m,iq=name==='الفجر'?25:name==='المغرب'?10:20;if(mins===base)prayerAlert(name,time,'adhan');if(mins===base+iq)prayerAlert(name,plusMinutes(time,iq),'iqama');}const entries=Object.entries(t).filter(([,v])=>v);if(entries.length){const next=entries.map(([n,v])=>{const [h,m]=v.split(':').map(Number);let d=h*60+m;if(d<=mins)d+=1440;return[n,d,v]}).sort((a,b)=>a[1]-b[1])[0];if(next){const remain=next[1]-mins;const iq=next[0]==='الفجر'?25:next[0]==='المغرب'?10:20;const el=$('ghNextPrayer');if(el)el.textContent='الصلاة القادمة: '+next[0]+' بعد '+remain+' دقيقة • الإقامة بعد '+iq+' دقيقة';}}}
  function patchPrayer(){
    const old=window.loadPrayerByMemberLocation;if(typeof old!=='function')return;
    window.loadPrayerByMemberLocation=async function(){try{await old();setTimeout(()=>{const map={الفجر:$('ptFajr')?.textContent,الظهر:$('ptDhuhr')?.textContent,العصر:$('ptAsr')?.textContent,المغرب:$('ptMaghrib')?.textContent,العشاء:$('ptIsha')?.textContent};prayerCache=map;for(const [n,v] of Object.entries(map)){const id={الفجر:'Fajr',الظهر:'Dhuhr',العصر:'Asr',المغرب:'Maghrib',العشاء:'Isha'}[n];if($('gh'+id+'A'))$('gh'+id+'A').textContent=v||'—';if($('gh'+id+'I'))$('gh'+id+'I').textContent=plusMinutes(v,n==='الفجر'?25:n==='المغرب'?10:20);}checkPrayerAlerts();},500);}catch(e){}};
  }

  const sportsSources=[
    ['دوري روشن السعودي','https://www.spl.com.sa/ar'],['الاتحاد السعودي','https://www.saff.com.sa/'],['كأس الملك','https://www.saff.com.sa/'],['كأس السوبر السعودي','https://www.saff.com.sa/']
  ];
  function sportsHtml(){return '<div class="hero"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><div><h2>⚽ الرياضة السعودية</h2><p class="muted">المباريات القادمة، الترتيب، كأس الملك، كأس السوبر، وأخبار الفرق واللاعبين.</p></div><button class="btn secondary" onclick="openPage(\'home\')">↩️ رجوع</button></div></div><div class="card"><div class="gh-sport-tabs"><button class="active" data-sp="rsl">دوري روشن</button><button data-sp="king">كأس الملك</button><button data-sp="super">كأس السوبر</button><button data-sp="news">أخبار الفرق واللاعبين</button></div><div id="ghSportsContent">جارٍ تحديث البيانات…</div></div><div class="card"><h3>🔗 المصادر الرسمية</h3><div class="links">'+sportsSources.map(x=>'<a target="_blank" rel="noopener" href="'+x[1]+'">⚽ '+x[0]+'</a>').join('')+'</div></div>'}
  async function loadSports(){const page=$('sports');if(!page)return;page.innerHTML=sportsHtml();page.querySelectorAll('[data-sp]').forEach(b=>b.onclick=()=>loadSportsTab(b.dataset.sp));await loadSportsTab('rsl');}
  async function espn(path){const u='https://site.api.espn.com/apis/site/v2/sports/soccer/ksa.1/'+path;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('ESPN '+r.status);return r.json();}
  function formatSportDate(v){try{return new Date(v).toLocaleString('ar-SA',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}catch{return v||'—'}}
  async function loadRsl(){const el=$('ghSportsContent');el.innerHTML='جارٍ جلب مباريات الأسبوع والترتيب…';try{const j=await espn('scoreboard?limit=100');const now=Date.now(),week=now+7*86400000;const events=(j.events||[]).filter(e=>{const d=new Date(e.date).getTime();return d>=now&&d<=week});let html='<h3>📅 المباريات القادمة خلال 7 أيام</h3>';html+=events.length?events.map(e=>{const c=e.competitions?.[0]||{},teams=c.competitors||[];const home=teams.find(t=>t.homeAway==='home')?.team?.displayName||'—',away=teams.find(t=>t.homeAway==='away')?.team?.displayName||'—';const b=(c.broadcasts||[]).map(x=>x.names?.join('،')).filter(Boolean).join('، ')||'غير محددة';return '<div class="gh-match"><div class="gh-team">'+esc(away)+'</div><div class="gh-match-time">'+formatSportDate(e.date)+'<div class="gh-channel">📺 '+esc(b)+'</div></div><div class="gh-team">'+esc(home)+'</div></div>'}).join(''):'<p class="muted">لا توجد مباريات منشورة خلال الأيام السبعة القادمة في المصدر الحالي.</p>';
      try{const st=await espn('standings?limit=100');const entries=st?.standings?.entries||st?.children?.flatMap(x=>x.standings?.entries||[])||[];const rows=entries.sort((a,b)=>(b.stats?.find(s=>s.name==='points')?.value||0)-(a.stats?.find(s=>s.name==='points')?.value||0));html+='<h3>🏆 الترتيب حسب النقاط</h3><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>الفريق</th><th>لعب</th><th>ف</th><th>ت</th><th>خ</th><th>نقاط</th></tr></thead><tbody>'+rows.map((r,i)=>{const stat=n=>r.stats?.find(s=>s.name===n)?.value??'—';return '<tr><td>'+(i+1)+'</td><td>'+esc(r.team?.displayName||'—')+'</td><td>'+stat('gamesPlayed')+'</td><td>'+stat('wins')+'</td><td>'+stat('ties')+'</td><td>'+stat('losses')+'</td><td><b>'+stat('points')+'</b></td></tr>'}).join('')+'</tbody></table></div>'}catch(e){html+='<p class="muted">تعذر جلب جدول الترتيب من المصدر الرياضي الحالي.</p>'}el.innerHTML=html;
    }catch(e){el.innerHTML='<p class="muted">تعذر تحديث بيانات دوري روشن الآن. استخدم المصادر الرسمية أدناه.</p>'}}
  async function loadSportsTab(tab){if(tab==='rsl')return loadRsl();const el=$('ghSportsContent');if(!el)return;if(tab==='king')el.innerHTML='<h3>🏆 كأس الملك</h3><p class="muted">النتائج والمواعيد تتغير حسب إعلان الاتحاد السعودي. سيتم ربط الجدول المباشر عند توفر مصدر بيانات موثوق للمسابقة.</p><div class="links"><a target="_blank" rel="noopener" href="https://www.saff.com.sa/">الاتحاد السعودي لكرة القدم</a></div>';else if(tab==='super')el.innerHTML='<h3>🏆 كأس السوبر السعودي</h3><p class="muted">متابعة المواعيد والنتائج عبر المصدر الرسمي للاتحاد السعودي.</p><div class="links"><a target="_blank" rel="noopener" href="https://www.saff.com.sa/">الاتحاد السعودي لكرة القدم</a></div>';else el.innerHTML='<h3>📰 أخبار الفرق واللاعبين</h3><div class="gh-news"><a target="_blank" href="https://www.spl.com.sa/ar">أخبار دوري روشن الرسمية</a><a target="_blank" href="https://www.saff.com.sa/">أخبار الاتحاد السعودي والمسابقات</a><a target="_blank" href="https://www.alarabiya.net/sport/saudi-sport">العربية — الرياضة السعودية</a><a target="_blank" href="https://www.kooora.com/">كووورة — أخبار ومتابعة الفرق واللاعبين</a></div>';}

  function servicesHtml(){const items=[['🏛️','بلدي','https://balady.gov.sa/ar/services'],['🪪','أبشر','https://www.absher.sa/'],['🏥','صحتي','https://www.moh.gov.sa/eServices/Pages/cassystem.aspx'],['⚡','الشركة السعودية للكهرباء','https://www.se.com.sa/'],['💧','المياه الوطنية','https://www.nwc.com.sa/'],['🚓','الشرطة والجهات الأمنية','https://www.moi.gov.sa/'],['🚑','الهلال الأحمر','https://srca.org.sa/'],['🏥','البحث عن مستشفى قريب','https://www.google.com/maps/search/مستشفى+قريب+من+موقعي'],['💊','البحث عن صيدلية قريبة','https://www.google.com/maps/search/صيدلية+قريبة+من+موقعي'],['🕌','المساجد القريبة','https://www.google.com/maps/search/مساجد+قريبة+من+موقعي'],['🛒','المتاجر والخدمات القريبة','https://www.google.com/maps/search/خدمات+قريبة+من+موقعي'],['🗑️','بلاغات النظافة والبلدية','https://balady.gov.sa/ar/services'],['🚗','مواعيد المرور والخدمات المرورية','https://www.absher.sa/'],['📦','البريد السعودي سبل','https://splonline.com.sa/'],['📞','أرقام الطوارئ السعودية','https://www.gov.sa/wps/portal/snp/aboutksa/emergencycontacts'],['🏠','خدمات العقار والإسكان','https://sakani.sa/']];return '<div class="hero"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><h2 style="margin:0">🏘️ خدمات الحي</h2><button class="btn secondary" onclick="openPage(\'home\')">↩️ رجوع</button></div><p class="muted">الخدمات المهمة للحي مجمعة في صفحة واحدة، مع روابط الجهات الرسمية والبحث عن الخدمات القريبة.</p></div><div class="grid">'+items.map(x=>'<a class="card icon-card gh-service" target="_blank" rel="noopener" href="'+x[2]+'"><span class="icon">'+x[0]+'</span><span><b>'+x[1]+'</b><br><small>فتح الخدمة</small></span></a>').join('')+'</div>'}

  function patchQuran(){
    // Quran Foundation exposes explicit Uthmani fields; use it as the primary text source when available.
    window.ghQuranSource='Quran Foundation — Uthmani';
    const oldEnsure=window.ensureQuranSurahLoaded;
    if(typeof oldEnsure!=='function')return;
    window.ensureQuranSurahLoaded=async function(id){try{const u='https://api.quran.com/api/v4/verses/by_chapter/'+id+'?language=ar&words=false&fields=text_uthmani&per_page=300';const j=await fetch(u,{cache:'force-cache'}).then(r=>{if(!r.ok)throw Error('Quran '+r.status);return r.json()});const s=(window.QURAN_DATA?.surahs||[]).find(x=>x.id===Number(id));if(s){s.verses=(j.verses||[]).map(v=>({id:Number(v.verse_number||v.id),text:String(v.text_uthmani||'')}));s.total_verses=s.verses.length;return s;}return oldEnsure(id);}catch(e){return oldEnsure(id)}};
  }

  function boot(){injectStyle();mountWeather();addPrayerUI();patchPrayer();patchQuran();loadSports();const sv=$('services');if(sv)sv.innerHTML=servicesHtml();setInterval(()=>{if(document.visibilityState==='visible')checkPrayerAlerts()},30000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
