/* Ghadeer UI v3 — compact navigation, services hub, football, Quran, and functional icons. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast=(m,ok=true)=>window.toast?window.toast(m,ok):console.log(m);
  const cfg=()=>window.GHADEER_SUPABASE_CONFIG||{};
  const db=()=>window.supabase?.createClient?.(cfg().url,cfg().key);
  const auth=()=>({id:Number(window.state?.member?.id)||0,pin:window.state?.pin||''});
  function style(){
    if($('ghV3Style'))return;
    const s=document.createElement('style');s.id='ghV3Style';s.textContent=`
      .gh-v3-shell{margin:0 0 12px}.gh-v3-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.gh-v3-head h2{margin:0;color:var(--g);font-size:22px}.gh-v3-head p{margin:3px 0 0;color:var(--muted);font-size:12px}
      .gh-v3-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.gh-v3-tile{border:1px solid var(--line);background:#fff;border-radius:17px;padding:12px 9px;text-align:center;min-height:92px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;box-shadow:0 3px 12px #00000008;cursor:pointer}.gh-v3-tile:hover{transform:translateY(-1px)}.gh-v3-tile .i{font-size:29px;line-height:1}.gh-v3-tile b{font-size:13px}.gh-v3-tile small{color:var(--muted);font-size:10px}
      .gh-v3-feature{background:linear-gradient(135deg,#fffdf7,#f1f8f3);border:1px solid #dfe7df;border-radius:18px;padding:13px;margin-bottom:10px}.gh-v3-row{display:flex;gap:7px;overflow:auto;padding-bottom:2px}.gh-v3-chip{white-space:nowrap;border:1px solid var(--line);background:#fff;border-radius:999px;padding:8px 11px;font-weight:800;color:var(--g)}
      .gh-v3-modal{position:fixed;inset:0;background:#0007;z-index:90;display:grid;place-items:center;padding:14px}.gh-v3-modal.hidden{display:none!important}.gh-v3-modal-card{width:min(600px,100%);max-height:88vh;overflow:auto;background:#fff;border-radius:20px;border:1px solid var(--line);padding:16px;box-shadow:0 20px 70px #0005}.gh-v3-modal-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.gh-v3-close{border:0;background:#eee8de;border-radius:50%;width:38px;height:38px;font-size:23px}
      .gh-v3-list{display:grid;gap:8px}.gh-v3-item{border:1px solid var(--line);border-radius:13px;padding:10px;background:#fff}.gh-v3-item b{font-size:14px}.gh-v3-item p{margin:4px 0;color:#5d574f;font-size:12px;line-height:1.7}.gh-q3-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin:10px 0}.gh-q3-action{border:1px solid #d8c9ad;background:linear-gradient(135deg,#fffdf8,#f4faf6);border-radius:17px;padding:13px;text-align:right;cursor:pointer}.gh-q3-action .qi{font-size:27px}.gh-q3-action b{display:block;margin-top:5px}.gh-q3-action small{color:var(--muted)}.gh-q3-reader{background:#fffdf8;border:1px solid #d8c9ad;border-radius:18px;padding:13px}.gh-q3-ayah{font-family:"Amiri Quran","Amiri","Traditional Arabic",serif;font-size:24px;line-height:2.2;padding:12px 5px;border-bottom:1px solid #eadfce}.gh-q3-ayah:last-child{border-bottom:0}.gh-q3-toolbar{display:grid;grid-template-columns:1fr 1fr;gap:7px}.gh-q3-status{font-size:12px;color:var(--muted);margin:7px 0}.gh-q3-rule{padding:9px;border-radius:12px;background:#f4faf6;border:1px solid #dcebe1;margin:6px 0;line-height:1.8;font-size:12px}
      .gh-v3-nav{position:fixed!important;bottom:0;left:0;right:0;background:#fff!important;border-top:1px solid var(--line);z-index:80;display:grid!important;grid-template-columns:repeat(5,1fr);max-width:none!important}.gh-v3-nav button{max-width:none!important;border:0!important;background:#fff!important;padding:8px 3px!important;font-size:11px!important;color:var(--muted)!important}.gh-v3-nav button.active{color:var(--g)!important;background:#f4faf6!important;font-weight:900}
      @media(max-width:650px){.gh-v3-grid{grid-template-columns:repeat(3,1fr)}.gh-q3-actions{grid-template-columns:1fr 1fr}.gh-q3-toolbar{grid-template-columns:1fr}.gh-v3-tile{min-height:86px;padding:10px 5px}.gh-v3-tile .i{font-size:26px}}
    `;document.head.appendChild(s);
  }
  function tile(icon,title,desc,action){return `<button type="button" class="gh-v3-tile" data-v3-action="${esc(action)}"><span class="i">${icon}</span><b>${esc(title)}</b><small>${esc(desc)}</small></button>`}
  function makePage(id,title,icon){let p=$(id);if(!p){p=document.createElement('section');p.id=id;p.className='page';document.querySelector('main.wrap')?.appendChild(p)}p.innerHTML=`<div class="hero"><div class="gh-v3-head"><div><h2>${icon} ${esc(title)}</h2><p>واجهة مختصرة بدون تكرار — كل وظيفة في مكان واحد.</p></div><button type="button" class="btn secondary" data-v3-home>↩️ الرئيسية</button></div></div><div id="${id}-body"></div>`;p.querySelector('[data-v3-home]').onclick=()=>window.openPage?.('home');return p}
  function replaceHomeQuickGrid(){const home=$('home');if(!home)return;[...home.querySelectorAll('.grid')].forEach(g=>{const txt=g.textContent||'';if(/الطلعات/.test(txt)&&/القرآن/.test(txt)&&/الرياضة/.test(txt)&&/خدمات الحي/.test(txt))g.style.display='none'});let hub=$('ghHomeHub');if(!hub){hub=document.createElement('section');hub.id='ghHomeHub';hub.className='gh-v3-shell card';hub.innerHTML=`<div class="gh-v3-head"><div><h2>✨ خدمات الحي</h2><p>الوصول السريع بدون تكرار</p></div><button type="button" class="btn secondary" data-v3-all>كل الخدمات</button></div><div class="gh-v3-grid">${tile('☕','القهوة','الموعد القادم','coffee')+tile('🚐','الطلعات','موعد وتقييم','outings')+tile('🤝','الخدمات','طلب أو عرض خدمة','ghServicesHub')+tile('💼','الوظائف','حكومي وخاص','jobs')+tile('🛍️','سوق الحي','بيع وطلب','ghServicesHub:market')+tile('🎉','المناسبات','فعاليات الحي','neighborhoodEvents')+tile('⚽','كرة الحي','مباريات وتنظيم','ghFootball')+tile('📖','القرآن','مصحف وتلاوة','dhikr')+tile('❤️','تفقد جار','مساعدة وتواصل','neighborCheck')+tile('📰','الأخبار','أخبار الحي والمصادر','news')+tile('🕌','الصلاة','مواقيت الصلاة','homePrayer')+tile('🌤️','الطقس','طقس أبها','homeWeather')}</div>`;const anchor=home.querySelector('.hadith-board');anchor?anchor.insertAdjacentElement('afterend',hub):home.appendChild(hub);hub.querySelector('[data-v3-all]').onclick=()=>window.openPage?.('ghServicesHub');hub.querySelectorAll('[data-v3-action]').forEach(b=>b.onclick=()=>doAction(b.dataset.v3Action))}}
  function replaceNav(){const nav=document.querySelector('.bottom-nav');if(!nav)return;nav.classList.add('gh-v3-nav');nav.innerHTML=`<button type="button" data-page="home">🏠<br>الرئيسية</button><button type="button" data-page="ghServicesHub">🧰<br>الخدمات</button><button type="button" data-page="coffee">☕<br>القهوة</button><button type="button" data-page="members">👥<br>الجيران</button><button type="button" data-page="ghMore">☰<br>المزيد</button>`;nav.querySelectorAll('[data-page]').forEach(b=>b.onclick=e=>{e.preventDefault();window.openPage?.(b.dataset.page);nav.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
  function buildServices(){const p=makePage('ghServicesHub','خدمات الحي','🧰'),body=p.querySelector('#ghServicesHub-body');body.innerHTML=`<div class="gh-v3-feature"><b>منصة الحي في صفحة واحدة</b><p class="muted">الوظائف ضمن الخدمات، والطلعات لها مكان واحد فقط، والأيقونات مرتبة حسب الاستخدام.</p></div><div class="gh-v3-grid">${tile('🤝','خدمات الجيران','اطلب أو اعرض خدمة','services:help')+tile('🛍️','سوق الحي','منتجات وأغراض','services:market')+tile('💼','الوظائف','حكومي وخاص','jobs')+tile('🏠','العقار','بيع وإيجار','realEstate')+tile('🚐','الطلعات','المواعيد والتقييم','outings')+tile('🎉','مناسبات الحي','فعاليات ومناسبات','neighborhoodEvents')+tile('⚽','كرة الحي','مباراة وحضور ونتيجة','ghFootball')+tile('📖','القرآن','مصحف وتلاوة','dhikr')+tile('📰','الأخبار والصحف','مصادر وأخبار','news')+tile('❤️','تفقد جار','حالات مساعدة','neighborCheck')+tile('📢','الإعلانات','إعلانات الحي','messages')+tile('🔎','المفقودات','بحث وإبلاغ','messages')}</div><div class="gh-v3-feature"><b>أيقونات سريعة</b><div class="gh-v3-row"><button class="gh-v3-chip" data-v3-action="homePrayer">🕌 الصلاة</button><button class="gh-v3-chip" data-v3-action="homeWeather">🌤️ الطقس</button><button class="gh-v3-chip" data-v3-action="members">👥 الجيران</button><button class="gh-v3-chip" data-v3-action="messages">💬 الرسائل</button></div></div>`;body.querySelectorAll('[data-v3-action]').forEach(b=>b.onclick=()=>doAction(b.dataset.v3Action))}
  function buildMore(){const p=makePage('ghMore','المزيد','☰'),body=p.querySelector('#ghMore-body');body.innerHTML=`<div class="gh-v3-grid">${tile('🎉','المناسبات','فعاليات الحي','neighborhoodEvents')}${tile('📰','الأخبار','الأخبار والمصادر','news')}${tile('🏠','العقار','بيع وإيجار','realEstate')}${tile('📖','القرآن','المصحف والأذكار','dhikr')}${tile('⚽','الرياضة','كرة الحي والمصادر','ghFootball')}${tile('❤️','تفقد جار','المساعدة','neighborCheck')}${tile('💬','الرسائل','التواصل','messages')}${tile('🔐','دخول الإدارة','للمخولين','manager')}${tile('🛠️','المطور','إدارة البرنامج','developer')}${tile('🚪','خروج','تسجيل الخروج','logout')}</div>`;body.querySelectorAll('[data-v3-action]').forEach(b=>b.onclick=()=>doAction(b.dataset.v3Action))}
  function buildFootball(){const p=makePage('ghFootball','كرة الحي','⚽'),body=p.querySelector('#ghFootball-body');body.innerHTML=`<div class="gh-v3-feature"><b>⚽ كرة الحي — تنظيم بدل روابط فقط</b><p class="muted">أنشئ دعوة لمباراة أو تمرين، شارك الموعد والملعب، ثم تظهر المشاركات للجيران.</p><div class="gh-v3-row"><button class="btn primary" id="ghFootAdd">＋ أعلن عن مباراة</button><a class="btn secondary" target="_blank" rel="noopener" href="https://www.spl.com.sa/">دوري روشن</a><a class="btn secondary" target="_blank" rel="noopener" href="https://www.saff.com.sa/">الاتحاد السعودي</a></div></div><div class="card"><h3>المباريات والأنشطة المنشورة</h3><div id="ghFootList" class="gh-v3-list"><p class="muted">جارٍ التحميل…</p></div></div>`;body.querySelector('#ghFootAdd').onclick=()=>footballModal();loadFootball()}
  async function loadFootball(){const el=$('ghFootList');if(!el)return;try{const c=db();if(!c){el.innerHTML='<p class="muted">قاعدة البيانات غير متاحة.</p>';return}const r=await c.rpc('list_neighbor_services');if(r.error)throw r.error;const rows=r.data?.initiatives||[];el.innerHTML=rows.length?rows.slice(0,12).map(x=>`<article class="gh-v3-item"><b>⚽ ${esc(x.title||'مباراة الحي')}</b><p>${esc(x.description||'')}</p><small class="muted">مبادرة من سكان الحي</small></article>`).join(''):'<p class="muted">لا توجد مباريات منشورة. أضف أول مباراة.</p>'}catch(e){el.innerHTML='<p class="muted">تعذر تحميل مباريات الحي حاليًا.</p>'}}
  function footballModal(){modal('إعلان مباراة في الحي',`<label>اسم المباراة/النشاط<input id="ghFootTitle" placeholder="مثال: مباراة الجمعة"></label><label>الموعد والمكان<input id="ghFootDesc" placeholder="الجمعة 9:00م — ملعب الحي — العدد 10"></label><button class="btn primary" id="ghFootSave">نشر المباراة</button>`,async()=>{const b=$('ghFootSave');b.onclick=async()=>{const a=auth();if(!a.id||!a.pin){if(window.showMemberAuth)window.showMemberAuth();toast('سجّل الدخول أولًا');return}const c=db();const r=await c.rpc('create_neighbor_initiative',{p_member_id:a.id,p_pin:a.pin,p_title:'⚽ '+$('ghFootTitle').value.trim(),p_description:$('ghFootDesc').value.trim()});if(r.error||r.data?.success===false)return toast(r.error?.message||r.data?.message||'تعذر النشر',false);closeModal();toast('تم نشر مباراة الحي');loadFootball()}})}
  let q3={chapters:[],surah:1,verses:[]};
  function qdb(){return new Promise((res,rej)=>{const r=indexedDB.open('ghadeer-quran-v3',1);r.onupgradeneeded=()=>r.result.createObjectStore('surahs',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function qGet(id){try{const d=await qdb();return await new Promise((res,rej)=>{const x=d.transaction('surahs').objectStore('surahs').get(id);x.onsuccess=()=>res(x.result?.verses||null);x.onerror=()=>rej(x.error)})}catch(e){return null}}
  async function qPut(id,verses){try{const d=await qdb();d.transaction('surahs','readwrite').objectStore('surahs').put({id,verses})}catch(e){}}
  async function qChapters(){if(q3.chapters.length)return q3.chapters;const r=await fetch('https://api.quran.com/api/v4/chapters?language=ar');if(!r.ok)throw Error();q3.chapters=(await r.json()).chapters||[];return q3.chapters}
  async function qVerses(id){const cached=await qGet(id);if(cached)return cached;const r=await fetch('https://api.quran.com/api/v4/verses/by_chapter/'+id+'?language=ar&words=false&fields=text_uthmani,text_qpc_hafs&per_page=300');if(!r.ok)throw Error();const v=(await r.json()).verses||[];await qPut(id,v);return v}
  function audio(key){const [s,a]=key.split(':').map(Number);return 'https://everyayah.com/data/Alafasy_128kbps/'+String(s).padStart(3,'0')+String(a).padStart(3,'0')+'.mp3'}
  function buildQuran(){const p=$('dhikr');if(!p)return;p.innerHTML=`<div class="hero"><div class="gh-v3-head"><div><h2>📖 القرآن والأذكار</h2><p>مصحف عثماني — رواية حفص عند توفر النص — تلاوة وحفظ وتفسير وأذكار.</p></div><button class="btn secondary" id="ghQDownload">⬇️ تنزيل السورة</button></div></div><div class="gh-q3-actions"><button class="gh-q3-action" id="ghQRead"><span class="qi">🎙️</span><b>تصحيح التلاوة</b><small>قراءة صوتية ومطابقة أولية للنص</small></button><button class="gh-q3-action" id="ghQTajweed"><span class="qi">🧠</span><b>مساعد التجويد</b><small>قواعد ومراجعة نطق أولية</small></button><button class="gh-q3-action" id="ghQMushaf"><span class="qi">📖</span><b>المصحف والتلاوة</b><small>السور والآيات والصوت والحفظ</small></button><button class="gh-q3-action" id="ghQTafsir"><span class="qi">📚</span><b>تفسير الآية</b><small>فتح تفسير الآية المحددة</small></button><button class="gh-q3-action" id="ghQAdhkar"><span class="qi">🤲</span><b>الأذكار</b><small>أذكار يومية مختصرة</small></button><button class="gh-q3-action" id="ghQHifz"><span class="qi">🧠</span><b>اختبر حفظي</b><small>إخفاء الآية واسترجاعها</small></button></div><div class="gh-q3-reader"><div class="gh-q3-toolbar"><select id="ghQSurah"><option>جارٍ تحميل السور…</option></select><select id="ghQAyah"><option>اختر الآية</option></select></div><div class="gh-q3-status" id="ghQStatus"></div><div id="ghQContent"></div></div>`;$('ghQRead').onclick=()=>qRead();$('ghQTajweed').onclick=()=>qTajweed();$('ghQMushaf').onclick=()=>qRender();$('ghQTafsir').onclick=()=>qTafsir();$('ghQAdhkar').onclick=()=>qAdhkar();$('ghQHifz').onclick=()=>qHifz();$('ghQDownload').onclick=()=>qDownload();bootQuran()}
  async function bootQuran(){try{const cs=await qChapters();const s=$('ghQSurah');s.innerHTML=cs.map(c=>`<option value="${c.id}">${c.id} — ${esc(c.name_ar||c.name_simple)}</option>`).join('');s.value=q3.surah;s.onchange=async()=>{q3.surah=Number(s.value);q3.verses=await qVerses(q3.surah);fillAyahs();qRender()};q3.verses=await qVerses(q3.surah);fillAyahs();qRender()}catch(e){$('ghQStatus').textContent='تعذر تحميل المصحف من المصدر الآن.'}}
  function fillAyahs(){const s=$('ghQAyah');s.innerHTML='<option value="">كل الآيات</option>'+q3.verses.map(v=>`<option value="${v.verse_key}">الآية ${v.verse_number}</option>`).join('');s.onchange=()=>qRender()}
  function qRender(){const out=$('ghQContent');if(!out)return;const selected=$('ghQAyah')?.value;const arr=selected?q3.verses.filter(v=>v.verse_key===selected):q3.verses.slice(0,30);out.innerHTML=arr.map(v=>`<div class="gh-q3-ayah" id="ghqa-${v.verse_key.replace(':','-')}"><span class="ayah-no">﴿${v.verse_number}﴾</span> ${esc(v.text_uthmani||v.text_qpc_hafs||'')} <button class="small-btn" data-qplay="${v.verse_key}">🔊</button> <button class="small-btn" data-qmark="${v.verse_key}">⭐</button></div>`).join('');out.querySelectorAll('[data-qplay]').forEach(b=>b.onclick=()=>new Audio(audio(b.dataset.qplay)).play().catch(()=>window.open(audio(b.dataset.qplay),'_blank','noopener')));out.querySelectorAll('[data-qmark]').forEach(b=>b.onclick=()=>{const k=b.dataset.qmark;let a=JSON.parse(localStorage.getItem('gh_qv3_marks')||'[]');a=a.includes(k)?a.filter(x=>x!==k):[...a,k];localStorage.setItem('gh_qv3_marks',JSON.stringify(a));b.textContent=a.includes(k)?'⭐':'☆'});$('ghQStatus').textContent='تم تحميل '+q3.verses.length+' آية — تُحفظ السورة في الجهاز بعد تحميلها.'}
  async function qDownload(){try{q3.verses=await qVerses(q3.surah);toast('تم تنزيل السورة للجهاز للاستخدام دون اتصال عند توفر المتصفح.')}catch(e){toast('تعذر تنزيل السورة',false)}}
  function qTafsir(){const k=$('ghQAyah')?.value;if(!k)return toast('اختر آية أولًا');window.open('https://tafsir.app/'+k,'_blank','noopener')}
  function qAdhkar(){modal('🤲 الأذكار',`<div class="gh-v3-list"><div class="gh-v3-item"><b>أذكار الصباح</b><p>سبحان الله وبحمده — 100 مرة.</p></div><div class="gh-v3-item"><b>الاستغفار</b><p>أستغفر الله وأتوب إليه.</p></div><div class="gh-v3-item"><b>الصلاة على النبي ﷺ</b><p>اللهم صل وسلم على نبينا محمد.</p></div></div><p class="muted">للنصوص الموسعة استخدم المصدر الموثوق في حصن المسلم.</p><a class="btn secondary" target="_blank" rel="noopener" href="https://hisnmuslim.com/">فتح حصن المسلم</a>`)}
  function qHifz(){const v=q3.verses[Math.floor(Math.random()*Math.max(1,q3.verses.length))];if(!v)return;modal('🧠 اختبار حفظ',`<p class="muted">أكمل الآية من حفظك ثم اكشف النص.</p><textarea id="ghQAnswer" rows="4" placeholder="اكتب ما تحفظه…"></textarea><button class="btn primary" id="ghQReveal">كشف النص</button><div id="ghQRevealBox"></div>`);$('ghQReveal').onclick=()=>{const box=$('ghQRevealBox');if(box)box.innerHTML='<div class="gh-v3-item"><b>النص:</b><p class="gh-q3-ayah">'+esc(v.text_uthmani||v.text_qpc_hafs||'')+'</p></div>'}}
  function qRead(){const k=$('ghQAyah')?.value;const v=q3.verses.find(x=>x.verse_key===k)||q3.verses[0];if(!v)return;modal('🎙️ تصحيح التلاوة',`<p class="muted">اقرأ الآية بعد الضغط على الميكروفون. النتيجة مطابقة صوتية أولية وليست حكمًا تجويديًا.</p><div class="gh-v3-item"><p class="gh-q3-ayah">${esc(v.text_uthmani||v.text_qpc_hafs||'')}</p></div><button class="btn primary" id="ghQMic">🎙️ ابدأ القراءة</button><div id="ghQSpeech" class="gh-v3-item"></div>`);$('ghQMic').onclick=()=>startSpeech(v,'ghQSpeech')}
  function qTajweed(){const k=$('ghQAyah')?.value;const v=q3.verses.find(x=>x.verse_key===k)||q3.verses[0];if(!v)return;modal('🧠 مساعد التجويد',`<div class="gh-q3-rule"><b>النون الساكنة والتنوين:</b> راقب الإظهار والإدغام والإقلاب والإخفاء بحسب الحرف التالي.</div><div class="gh-q3-rule"><b>الميم الساكنة:</b> راقب الإخفاء الشفوي والإدغام والإظهار الشفوي.</div><div class="gh-q3-rule"><b>المدود:</b> انتبه لمواضع المد وعدم اختصار الصوت.</div><div class="gh-v3-item"><p class="gh-q3-ayah">${esc(v.text_uthmani||v.text_qpc_hafs||'')}</p></div><button class="btn primary" id="ghQTajMic">🎙️ فحص القراءة</button><div id="ghQTajOut" class="gh-v3-item"></div>`);$('ghQTajMic').onclick=()=>startSpeech(v,'ghQTajOut')}
  function startSpeech(v,outId){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech)return toast('التعرف الصوتي غير مدعوم في هذا المتصفح.',false);const r=new Speech();r.lang='ar-SA';r.interimResults=false;r.maxAlternatives=1;const out=$(outId);if(out)out.textContent='جارٍ الاستماع…';r.onresult=e=>{const said=e.results[0][0].transcript||'';const clean=x=>x.replace(/[ًٌٍَُِّْـٰۖۗۚۛ]/g,'').replace(/[^\u0621-\u063A\u0641-\u064A\s]/g,'').replace(/\s+/g,' ').trim();const a=clean(v.text_uthmani||v.text_qpc_hafs||'');const b=clean(said);const aw=new Set(a.split(' '));const bw=b.split(' ');const hit=bw.filter(x=>aw.has(x)).length;const score=bw.length?Math.round(hit/bw.length*100):0;if(out)out.innerHTML='<b>النص الملتقط:</b> '+esc(said)+'<br><b>مطابقة تقريبية:</b> '+score+'%'};r.onerror=()=>{if(out)out.textContent='تعذر التقاط الصوت.'};r.start()}
  let modalEl=null;function modal(title,html){closeModal();modalEl=document.createElement('div');modalEl.className='gh-v3-modal';modalEl.innerHTML=`<div class="gh-v3-modal-card"><div class="gh-v3-modal-head"><h2>${title}</h2><button class="gh-v3-close" aria-label="إغلاق">×</button></div>${html}</div>`;document.body.appendChild(modalEl);modalEl.querySelector('.gh-v3-close').onclick=closeModal;modalEl.addEventListener('click',e=>{if(e.target===modalEl)closeModal()})}
  function closeModal(){if(modalEl){modalEl.remove();modalEl=null}}
  function doAction(a){if(a==='homePrayer'){window.loadPrayerByMemberLocation?.();return}if(a==='homeWeather'){document.getElementById('ghWeatherBox')?.click();return}if(a==='logout'){window.logout?.();return}if(a==='services:help'){window.openPage?.('ghServicesHub');return}if(a==='services:market'||a==='ghServicesHub:market'){window.openPage?.('ghServicesHub');return}window.openPage?.(a)}
  function install(){style();replaceHomeQuickGrid();replaceNav();buildServices();buildMore();buildFootball();buildQuran();const legacy=$('ghNeighborhoodServices');if(legacy)legacy.style.display='none'}
  function boot(){install();[500,1500,3000,6000].forEach(ms=>setTimeout(install,ms))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
  window.GhadeerUIv3={install,closeModal};
})();
