/* Ghadeer UI v5.4 — canonical navigation, grouped services, fully customizable home. */
(()=>{'use strict';
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const catalog={services:[['🤝','خدمات الجيران','طلب أو عرض خدمة','services:help'],['🏠','سكن الحي','السكن والعقار','realEstate'],['💬','تواصل الجيران','تواصل ورسائل الحي','messages'],['🛍️','سوق الحي','بيع وشراء','services:market'],['💼','الوظائف','فرص العمل','jobs'],['🎉','مناسبات الحي','فعاليات','neighborhoodEvents'],['❤️','تفقد جار','مساعدة وتواصل','neighborCheck'],['📢','إعلانات الحي','إعلانات وتنبيهات','announcements'],['🔎','المفقودات','بحث وإبلاغ','lost'],['📰','أخبار الحي','أخبار ومصادر','news']],football:[['🇸🇦','دوري روشن','مباريات وترتيب وأخبار','spl'],['🇪🇺','الدوري الأوروبي','مباريات وترتيب وأخبار','uel'],['🌍','الدوريات العالمية','إنجلترا وإسبانيا وإيطاليا وألمانيا وفرنسا','world'],['👑','كأس الملك','المباريات والنتائج','king'],['🏆','السوبر السعودي','المباريات والنتائج','super'],['⚽','كورة حي الغدير','دوري ومباريات الحي','ghadeer']],wardi:[['📖','المصحف','114 سورة','read'],['🎙️','تصحيح التلاوة','قراءة ومتابعة','recite'],['🧠','التجويد','مساعد أحكام التجويد','tajweed'],['📚','التفسير','تفسير الآية','tafsir'],['🤲','الأذكار','أذكار يومية','adhkar'],['🧠','اختبر حفظي','اختبار الحفظ','hifz'],['⭐','علاماتي','آياتي المحفوظة','marks'],['⬇️','تنزيل المصحف','حفظ كامل المصحف على الجهاز','download']]};
const tile=(x,fn)=>`<button type="button" class="gh5-tile" data-gh5="${esc(fn)}"><span>${x[0]}</span><b>${esc(x[1])}</b><small>${esc(x[2])}</small></button>`;
function style(){if($('gh5Style'))return;const s=document.createElement('style');s.id='gh5Style';s.textContent=`.gh5-shell{background:#fff;border:1px solid var(--line);border-radius:22px;padding:14px;margin:12px 0}.gh5-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:12px}.gh5-head h2{margin:0;color:var(--g)}.gh5-head p{margin:4px 0;color:var(--muted);font-size:12px}.gh5-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.gh5-tile{position:relative;min-height:88px;border:1px solid var(--line);background:#fff;border-radius:17px;padding:10px 6px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;text-align:center;color:var(--txt);box-shadow:0 3px 12px #00000008;cursor:pointer}.gh5-tile:active{transform:scale(.98)}.gh5-tile span{font-size:27px;line-height:1}.gh5-tile b{font-size:13px}.gh5-tile small{font-size:10px;color:var(--muted)}.gh5-hidden{display:none!important}.gh5-nav{position:fixed!important;left:0;right:0;bottom:0;z-index:80;display:grid!important;grid-template-columns:repeat(5,1fr);background:#fff!important;border-top:1px solid var(--line)}.gh5-nav button{border:0!important;background:#fff!important;padding:8px 3px!important;font-size:11px!important;color:var(--muted)!important;cursor:pointer}.gh5-home-customize{white-space:nowrap}@media(max-width:650px){.gh5-grid{grid-template-columns:repeat(3,1fr)}.gh5-head{align-items:flex-start}.gh5-home-customize{font-size:11px;padding:8px 9px}}`;document.head.appendChild(s)}
function hideLegacy(){['ghHomeHub','ghNeighborhoodServices','ghMore','ghV4Home','ghV4Services'].forEach(id=>$(id)?.classList.add('gh5-hidden'));document.querySelectorAll('.gh-v3-nav,.gh-v4-nav').forEach(x=>x.classList.add('gh5-hidden'))}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const p=$(id);if(p){p.classList.remove('gh5-hidden');p.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}}
function openExisting(fn){if(fn==='realEstate')return window.openPage?.('realEstate');if(fn==='messages')return window.openPage?.('messages');if(fn==='jobs')return window.openPage?.('jobs');if(fn==='neighborhoodEvents')return window.openPage?.('neighborhoodEvents');if(fn==='news')return window.openPage?.('news');if(fn==='neighborCheck')return window.openPage?.('neighborCheck');if(fn==='announcements')return window.openPage?.('messages');if(fn==='lost')return window.openPage?.('lost');if(fn==='coffee')return window.openPage?.('coffee');if(fn==='outings')return window.openPage?.('outings');if(fn==='members')return window.openPage?.('members');if(fn==='manager')return window.openPage?.('manager');if(fn==='developer')return window.openPage?.('developer');if(fn==='settings')return window.openPage?.('settings');if(fn==='aboutProject')return window.openPage?.('aboutProject');if(fn==='logout')return window.logout?.()||window.signOut?.()}
function openQuranAction(key){const m=window.GhadeerQuran2Module;if(!m?.mount)return window.openPage?.('quran2');return Promise.resolve(m.mount()).then(()=>{if(key==='wardi'||key==='read'||key==='recite')return;const ids={tajweed:'tajweed',tafsir:'tafsir',adhkar:'adhkar',hifz:'hifz',marks:'bookmark',download:'offline'};const id=ids[key];const root=document.getElementById('quran2-root');if(!id||!root)return;root.querySelector(`[data-q2="${id}"]`)?.click()})}
function route(fn){if(fn==='services'||fn==='services:help'||fn==='services:market')return services();if(fn==='football'||['spl','uel','world','king','super','ghadeer'].includes(fn))return window.GhadeerFootballV2?.renderLeague?.(fn==='football'?'spl':fn);if(fn==='wardi'||['read','recite','tajweed','tafsir','adhkar','hifz','marks','download'].includes(fn))return openQuranAction(fn);if(fn==='home')return home();if(fn==='more')return more();return openExisting(fn)||window.openPage?.(fn)}
function bind(root){root.querySelectorAll('[data-gh5]').forEach(b=>{b.onclick=null;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();route(b.dataset.gh5)},{passive:false})})}
function section(id,title,desc,items){let p=$(id);if(!p){p=document.createElement('section');p.id=id;p.className='page';document.querySelector('main.wrap')?.appendChild(p)}p.innerHTML=`<div class="gh5-shell"><div class="gh5-head"><div><h2>${title}</h2><p>${desc}</p></div><button class="btn secondary" data-gh5="home">الرئيسية</button></div><div class="gh5-grid">${items.map(x=>tile(x,x[3])).join('')}</div></div>`;bind(p);show(id);return p}
function home(){hideLegacy();let p=$('gh5Home');if(!p){p=document.createElement('section');p.id='gh5Home';p.className='page';document.querySelector('main.wrap')?.appendChild(p)}p.innerHTML=`<div class="gh5-shell"><div class="gh5-head"><div><h2>🏘️ جيران حي الغدير</h2><p>الشاشة الرئيسية مرنة مثل شاشة الجوال — اضغط مطولاً للتخصيص.</p></div><button type="button" class="btn secondary gh5-home-customize" data-gh5-customize>✏️ تخصيص</button></div><div class="gh5-grid">${tile(['🧰','الخدمات','كل خدمات الحي'],'services')}${tile(['☕','القهوة','الجدول والتفاصيل'],'coffee')}${tile(['🚐','الطلعات','المواعيد والتقييمات'],'outings')}${tile(['⚽','الكورة','الدوريات والبطولات'],'football')}${tile(['📖','وردي','المصحف والتلاوة والأذكار'],'wardi')}${tile(['📰','أخبار الحي','أخبار ومصادر'],'news')}</div></div>`;bind(p);p.querySelector('[data-gh5-customize]')?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();window.GhadeerHomeCustomizer?.start?.()},{passive:false});show('gh5Home')}
function services(){hideLegacy();section('ghServicesHub','🧰 الخدمات','كل خدمات الحي في مركز واحد — بدون تكرار.',catalog.services)}
function football(active='spl'){hideLegacy();return window.GhadeerFootballV2?.renderLeague?.(active)}
function wardi(){hideLegacy();return openQuranAction('wardi')}
function more(){hideLegacy();let p=$('gh5More');if(!p){p=document.createElement('section');p.id='gh5More';p.className='page';document.querySelector('main.wrap')?.appendChild(p)}p.innerHTML=`<div class="gh5-shell"><div class="gh5-head"><div><h2>☰ المزيد</h2><p>الإدارة والإعدادات فقط.</p></div><button class="btn secondary" data-gh5="home">الرئيسية</button></div><div class="gh5-grid">${tile(['🔐','الإدارة','للمخولين فقط','manager'])}${tile(['🛠️','المطور','إدارة النظام','developer'])}${tile(['⚙️','الإعدادات','إعدادات الحساب','settings'])}${tile(['ℹ️','عن المشروع','المعلومات والحقوق','aboutProject'])}${tile(['🚪','خروج','تسجيل الخروج','logout'])}</div></div>`;bind(p);show('gh5More')}
function nav(){const n=document.querySelector('.bottom-nav');if(!n)return;n.className='bottom-nav gh5-nav';n.innerHTML=`<button data-gh5="home">🏠<br>الرئيسية</button><button data-gh5="services">🧰<br>الخدمات</button><button data-gh5="coffee">☕<br>القهوة</button><button data-gh5="members">👥<br>الجيران</button><button data-gh5="more">☰<br>المزيد</button>`;bind(n)}
function install(){style();hideLegacy();home();nav()}
function boot(){install()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.GhadeerUIv5={install,home,services,football,wardi,more};
})();