/* Ghadeer UI v5 — canonical information architecture. One entry per feature, children scoped to their parent. */
(()=>{'use strict';
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const catalog={services:[['🤝','خدمات الجيران','طلب أو عرض خدمة','services:help'],['🏠','سكن الحي','السكن والعقار','realEstate'],['💬','تواصل الجيران','تواصل ورسائل الحي','messages'],['🛍️','سوق الحي','بيع وشراء','services:market'],['💼','الوظائف','فرص العمل','jobs'],['🎉','مناسبات الحي','فعاليات','neighborhoodEvents'],['⚽','الكورة','كرة القدم والبطولات','football'],['📖','وردي','المصحف والتلاوة والأذكار','wardi'],['📰','أخبار الحي','أخبار ومصادر','news'],['❤️','تفقد جار','مساعدة وتواصل','neighborCheck'],['📢','إعلانات الحي','إعلانات','messages'],['🔎','المفقودات','بحث وإبلاغ','messages']],football:[['🇸🇦','دوري روشن','مباريات وترتيب وأخبار','spl'],['🇪🇺','الدوري الأوروبي','مباريات وترتيب وأخبار','uel'],['🌍','الدوريات العالمية','إنجلترا وإسبانيا وإيطاليا وألمانيا وفرنسا','world'],['👑','كأس الملك','المباريات والنتائج','king'],['🏆','السوبر السعودي','المباريات والنتائج','super'],['⚽','كورة حي الغدير','دوري ومباريات الحي','ghadeer']],wardi:[['📖','المصحف','114 سورة','read'],['🎙️','تصحيح التلاوة','قراءة ومتابعة','recite'],['🧠','التجويد','مساعد أحكام التجويد','tajweed'],['📚','التفسير','تفسير الآية','tafsir'],['🤲','الأذكار','أذكار يومية','adhkar'],['🧠','اختبر حفظي','اختبار الحفظ','hifz'],['⭐','علاماتي','آياتي المحفوظة','marks'],['⬇️','تنزيل المصحف','حفظ كامل المصحف على الجهاز','download']]};
const tile=(x,fn)=>`<button type="button" class="gh5-tile" data-gh5="${esc(fn)}"><span>${x[0]}</span><b>${esc(x[1])}</b><small>${esc(x[2])}</small></button>`;
function style(){if($('gh5Style'))return;const s=document.createElement('style');s.id='gh5Style';s.textContent=`.gh5-shell{background:#fff;border:1px solid var(--line);border-radius:22px;padding:14px;margin:12px 0}.gh5-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:12px}.gh5-head h2{margin:0;color:var(--g)}.gh5-head p{margin:4px 0;color:var(--muted);font-size:12px}.gh5-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.gh5-tile{min-height:88px;border:1px solid var(--line);background:#fff;border-radius:17px;padding:10px 6px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;text-align:center;color:var(--txt);box-shadow:0 3px 12px #00000008}.gh5-tile span{font-size:27px;line-height:1}.gh5-tile b{font-size:13px}.gh5-tile small{font-size:10px;color:var(--muted)}.gh5-hidden{display:none!important}.gh5-nav{position:fixed!important;left:0;right:0;bottom:0;z-index:80;display:grid!important;grid-template-columns:repeat(5,1fr);background:#fff!important;border-top:1px solid var(--line)}.gh5-nav button{border:0!important;background:#fff!important;padding:8px 3px!important;font-size:11px!important;color:var(--muted)!important}.gh5-feature{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:10px}.gh5-mini{border:1px solid var(--line);background:#fff;border-radius:16px;padding:12px;text-align:right}.gh5-mini b{display:block}.gh5-mini small{color:var(--muted)}@media(max-width:650px){.gh5-grid{grid-template-columns:repeat(3,1fr)}.gh5-feature{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function hideLegacy(){['ghHomeHub','ghNeighborhoodServices','ghMore','ghV4Home','ghV4Services'].forEach(id=>$(id)?.classList.add('gh5-hidden'));document.querySelectorAll('.gh-v3-nav').forEach(x=>x.classList.add('gh5-hidden'))}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const p=$(id);if(p){p.classList.remove('gh5-hidden');p.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}}
function route(fn){
 if(fn==='services:help'||fn==='services:market'){show('ghServicesHub');return}
 if(fn==='football'||['spl','uel','world','king','super','ghadeer'].includes(fn)){football(fn==='football'?'spl':fn);return}
 if(fn==='wardi'){wardi();return}
 if(fn==='home'){home();return}
 if(fn==='services'){services();return}
 if(fn==='more'){more();return}
 if(fn==='download'){const b=$('ghq5Download');if(b)b.click();else wardi();return}
 if(['read','recite'].includes(fn)){wardi();return}
 if(fn==='tajweed'){const b=$('ghq5Taj');if(b)b.click();else wardi();return}
 if(fn==='tafsir'){const b=$('ghq5Taf');if(b)b.click();else wardi();return}
 if(fn==='adhkar'){const b=$('ghq5Dh');if(b)b.click();else wardi();return}
 if(fn==='hifz'){const b=$('ghq5Hifz');if(b)b.click();else wardi();return}
 if(fn==='marks'){const b=$('ghq5Marks');if(b)b.click();else wardi();return}
 window.openPage?.(fn)
}
function bind(root){root.querySelectorAll('[data-gh5]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.onclick=()=>route(b.dataset.gh5)})}
function section(id,title,desc,items){let p=$(id);if(!p){p=document.createElement('section');p.id=id;p.className='page';document.querySelector('main.wrap')?.appendChild(p)}p.innerHTML=`<div class="gh5-shell"><div class="gh5-head"><div><h2>${title}</h2><p>${desc}</p></div><button class="btn secondary" data-gh5="home">الرئيسية</button></div><div class="gh5-grid">${items.map(x=>tile(x,x[3])).join('')}</div></div>`;bind(p);show(id);return p}
function home(){hideLegacy();let p=$('gh5Home');if(!p){p=document.createElement('section');p.id='gh5Home';p.className='page'}p.innerHTML=`<div class="gh5-shell"><div class="gh5-head"><div><h2>🏘️ جيران حي الغدير</h2><p>واجهة واحدة مرتبة — كل وظيفة في مكانها.</p></div><button class="btn secondary" data-gh5="services">🧰 الخدمات</button></div><div class="gh5-grid">${tile(catalog.services[0],'services:help')}${tile(catalog.services[1],'realEstate')}${tile(catalog.services[6],'football')}${tile(catalog.services[7],'wardi')}${tile(catalog.services[3],'services:market')}${tile(catalog.services[5],'neighborhoodEvents')}</div><div class="gh5-feature"><button class="gh5-mini" data-gh5="coffee"><b>☕ القهوة القادمة</b><small>الجدول والتفاصيل</small></button><button class="gh5-mini" data-gh5="outings"><b>🚐 الطلعات</b><small>الطلعات والتقييمات</small></button></div></div>`;document.querySelector('main.wrap')?.appendChild(p);bind(p);show('gh5Home')}
function services(){hideLegacy();section('ghServicesHub','🧰 الخدمات','كل الخدمات في مركز واحد — بدون تكرار.',catalog.services)}
function football(active='spl'){hideLegacy();let p=$('ghFootball');if(!p){p=document.createElement('section');p.id='ghFootball';p.className='page';document.querySelector('main.wrap')?.appendChild(p)}p.innerHTML=`<div class="gh5-shell"><div class="gh5-head"><div><h2>⚽ الكورة</h2><p>البطولات السعودية والأوروبية والعالمية + كورة حي الغدير.</p></div><button class="btn secondary" data-gh5="services">الخدمات</button></div><div class="gh5-grid">${catalog.football.map(x=>tile(x,x[3])).join('')}</div><div id="gh5FootballDetail" class="gh5-shell" style="margin:12px 0 0"></div></div>`;bind(p);const d=$('gh5FootballDetail');const c=catalog.football.find(x=>x[3]===active)||catalog.football[0];d.innerHTML=`<h3 style="margin-top:0">${c[0]} ${c[1]}</h3><p>${c[2]}</p><div class="gh5-grid"><button class="gh5-tile"><span>📅</span><b>المباريات القادمة</b><small>تُعرض هنا داخل التطبيق</small></button><button class="gh5-tile"><span>📊</span><b>الترتيب</b><small>جدول الفرق كاملًا</small></button><button class="gh5-tile"><span>📰</span><b>الأخبار</b><small>ملخص أخبار البطولة والفرق واللاعبين</small></button></div></div>`;show('ghFootball')}
function wardi(){hideLegacy();show('dhikr');window.GhadeerQuranV5?.init?.()}
function more(){hideLegacy();let p=$('gh5More');if(!p){p=document.createElement('section');p.id='gh5More';p.className='page';document.querySelector('main.wrap')?.appendChild(p)}p.innerHTML=`<div class="gh5-shell"><div class="gh5-head"><div><h2>☰ المزيد</h2><p>الإدارة والإعدادات فقط.</p></div><button class="btn secondary" data-gh5="home">الرئيسية</button></div><div class="gh5-grid">${tile(['🔐','الإدارة','للمخولين فقط','manager'],'manager')}${tile(['🛠️','المطور','إدارة النظام','developer'],'developer')}${tile(['⚙️','الإعدادات','إعدادات الحساب','settings'],'settings')}${tile(['ℹ️','عن المشروع','المعلومات والحقوق','aboutProject'],'aboutProject')}${tile(['🚪','خروج','تسجيل الخروج','logout'],'logout')}</div></div>`;bind(p);show('gh5More')}
function nav(){const n=document.querySelector('.bottom-nav');if(!n)return;n.className='bottom-nav gh5-nav';n.innerHTML=`<button data-gh5="home">🏠<br>الرئيسية</button><button data-gh5="services">🧰<br>الخدمات</button><button data-gh5="coffee">☕<br>القهوة</button><button data-gh5="members">👥<br>الجيران</button><button data-gh5="more">☰<br>المزيد</button>`;bind(n)}
function install(){style();hideLegacy();home();services();nav()}function boot(){install();[500,1200,2500,5000].forEach(ms=>setTimeout(install,ms))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.GhadeerUIv5={install,home,services,football,wardi};
})();
