const fs=require('fs');const path=require('path');
const errors=[];const warnings=[];const root=process.cwd();const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const build=read('build.js');const service=read('ghadeer-services-v6.js');const adapter=read('ghadeer-service-registry-adapter-v1.js');const entryMap=read('ghadeer-service-entry-map-v1.js');const index=read('index.html');
const buildScripts=[...build.matchAll(/const featureScripts=\[([\s\S]*?)\];/g)].flatMap(m=>[...m[1].matchAll(/["']([^"']+\.js)["']/g)].map(m=>m[1]));for(const f of buildScripts)if(!fs.existsSync(path.join(root,f)))errors.push(`missing build file: ${f}`);
for(const m of index.matchAll(/<script[^>]+src=["']([^"']+)["']/gi)){const f=m[1].split('?')[0];if(/^(https?:)?\/\//.test(f))continue;if(!fs.existsSync(path.join(root,f)))errors.push(`missing HTML script: ${f}`)}
const ids=[...index.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);const idCounts=new Map();for(const id of ids)idCounts.set(id,(idCounts.get(id)||0)+1);for(const [id,n] of idCounts)if(n>1)errors.push(`duplicate HTML id: ${id} (${n})`);
const records=[];const recRe=/\[\s*['"]([^'"]*)['"]\s*,\s*['"]([^'"]+)['"]\s*,\s*['"]([^'"]*)['"]\s*,\s*['"]([^'"]+)['"]\s*\]/g;let m;while((m=recRe.exec(service)))records.push({icon:m[1],name:m[2],description:m[3],category:m[4]});
const normalize=s=>String(s).replace(/[\sـ]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').toLowerCase();const names=new Map();for(const r of records){const k=normalize(r.name);if(names.has(k))errors.push(`duplicate service name: ${r.name} / ${names.get(k)}`);else names.set(k,r.name)}
if(!/R\.register\(\{serviceKey,name:x\.name/.test(adapter))errors.push('registry adapter does not register catalog services');
if(!/GhadeerServiceEntries/.test(adapter)||!/E\.register\(serviceKey\)\.entry/.test(adapter))errors.push('registry entry map contract missing');
if(!/host:'GhadeerServicesV6'/.test(entryMap)||!/serviceKey/.test(entryMap)||!/function register\(serviceKey\)/.test(entryMap))errors.push('service entry map implementation missing');
if(!/ownerPage:'services'/.test(adapter))errors.push('registry owner page contract missing');
const quranDir=path.join(root,'quran2');if(!fs.existsSync(quranDir))errors.push('missing quran2 module directory');else{for(const f of ['index.js','reader.js','reader-contract.js','reader-model.js','reader-view.js','navigation.js','audio.js','bookmarks.js','content-schema.js','tafsir.js','tajweed.js','hifz.js','recitation.js','search.js','offline.js','settings.js','reader.css'])if(!fs.existsSync(path.join(quranDir,f)))errors.push(`missing quran2 file: ${f}`);const q=read('quran2/index.js');if(!q.includes("serviceKey:'svc_quran2'")&&!q.includes("serviceKey: 'svc_quran2'"))errors.push('quran2 serviceKey missing');if(!q.includes("route:'/quran2'")&&!q.includes("route: '/quran2'"))errors.push('quran2 route missing');if(!q.includes('GhadeerQuran2Module'))errors.push('quran2 module entry missing');}
const routeMap=read('ghadeer-service-route-map-v1.js');const routeBridge=read('ghadeer-service-route-bridge-v1.js');if(/serviceKey:'svc_quran'/.test(routeMap)||/route:'\/quran'/.test(routeMap))errors.push('legacy Quran route remains canonical');if(!/serviceKey:'svc_quran2'/.test(routeMap)||!/route:'\/quran2'/.test(routeMap))errors.push('quran2 canonical route missing');if(!/module:'quran2'/.test(routeBridge))errors.push('quran2 route bridge missing');
const report={generatedAt:new Date().toISOString(),catalogCount:records.length,buildScriptCount:buildScripts.length,errors,warnings};fs.writeFileSync(path.join(root,'RELEASE_AUDIT_REPORT.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));if(errors.length)process.exit(1);