alter table public.neighbor_profiles add column if not exists residency_type text not null default 'unspecified' check (residency_type in ('owner','tenant','both','unspecified'));
alter table public.neighbor_profiles add column if not exists contact_in_app boolean not null default true;
alter table public.neighbor_profiles add column if not exists contact_whatsapp boolean not null default false;
alter table public.neighbor_profiles add column if not exists contact_phone boolean not null default false;
create index if not exists idx_neighbor_profiles_residency_type on public.neighbor_profiles(residency_type);

create table if not exists public.neighbor_message_reports (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.neighbor_messages(id) on delete cascade,
  reporter_id bigint not null references public.members(id) on delete cascade,
  reason text not null,
  created_at timestamptz not null default now(),
  unique(message_id,reporter_id)
);
create index if not exists idx_neighbor_message_reports_reporter on public.neighbor_message_reports(reporter_id,created_at desc);
alter table public.neighbor_message_reports enable row level security;

create or replace function public.set_neighbor_residency_type(p_member_id bigint,p_pin text,p_residency_type text) returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp as $$
declare ok boolean; begin
if p_residency_type not in ('owner','tenant','both','unspecified') then return jsonb_build_object('success',false,'message','صفة السكن غير صحيحة'); end if;
select exists(select 1 from public.members where id=p_member_id and active and pin_hash=extensions.crypt(p_pin,pin_hash)) into ok;
if not ok then return jsonb_build_object('success',false,'message','بيانات الدخول غير صحيحة'); end if;
insert into public.neighbor_profiles(member_id,residency_type) values(p_member_id,p_residency_type)
on conflict(member_id) do update set residency_type=excluded.residency_type,updated_at=now();
return jsonb_build_object('success',true); end; $$;
revoke all on function public.set_neighbor_residency_type(bigint,text,text) from public;
grant execute on function public.set_neighbor_residency_type(bigint,text,text) to anon,authenticated;

create or replace function public.neighbor_send_message(p_member_id bigint,p_pin text,p_recipient_id bigint,p_body text) returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp as $$
declare ok boolean; cid bigint; a bigint; b bigint; inapp boolean; blocked bigint; clean_body text:=trim(coalesce(p_body,'')); begin
select exists(select 1 from public.members where id=p_member_id and active and pin_hash=extensions.crypt(p_pin,pin_hash)) into ok;
if not ok then return jsonb_build_object('success',false,'message','بيانات الدخول غير صحيحة'); end if;
if p_recipient_id=p_member_id then return jsonb_build_object('success',false,'message','لا يمكن مراسلة نفسك'); end if;
if clean_body='' then return jsonb_build_object('success',false,'message','اكتب رسالة'); end if;
if length(clean_body)>2000 then return jsonb_build_object('success',false,'message','الرسالة طويلة جدًا'); end if;
if not exists(select 1 from public.members where id=p_recipient_id and active) then return jsonb_build_object('success',false,'message','الجار غير متاح'); end if;
a:=least(p_member_id,p_recipient_id); b:=greatest(p_member_id,p_recipient_id);
select blocked_by into blocked from public.neighbor_conversations where member_a=a and member_b=b;
if blocked is not null then return jsonb_build_object('success',false,'message','المحادثة محظورة'); end if;
select coalesce((select in_app_enabled from public.neighbor_message_settings where member_id=p_recipient_id),true) into inapp;
if not inapp then return jsonb_build_object('success',false,'message','هذا الجار لا يستقبل رسائل داخل البرنامج'); end if;
insert into public.neighbor_conversations(member_a,member_b,last_message_at) values(a,b,now()) on conflict(member_a,member_b) do update set last_message_at=now() returning id into cid;
insert into public.neighbor_messages(conversation_id,sender_id,body) values(cid,p_member_id,clean_body);
return jsonb_build_object('success',true,'conversation_id',cid); end; $$;
revoke all on function public.neighbor_send_message(bigint,text,bigint,text) from public;
grant execute on function public.neighbor_send_message(bigint,text,bigint,text) to anon,authenticated;

create or replace function public.report_neighbor_message(p_member_id bigint,p_pin text,p_message_id bigint,p_reason text) returns jsonb language plpgsql security definer set search_path=public,extensions,pg_temp as $$
declare ok boolean; conv_id bigint; begin
select exists(select 1 from public.members where id=p_member_id and active and pin_hash=extensions.crypt(p_pin,pin_hash)) into ok;
if not ok then return jsonb_build_object('success',false,'message','بيانات الدخول غير صحيحة'); end if;
select conversation_id into conv_id from public.neighbor_messages where id=p_message_id;
if conv_id is null or not exists(select 1 from public.neighbor_conversations where id=conv_id and (member_a=p_member_id or member_b=p_member_id)) then return jsonb_build_object('success',false,'message','الرسالة غير متاحة'); end if;
insert into public.neighbor_message_reports(message_id,reporter_id,reason) values(p_message_id,p_member_id,left(trim(coalesce(p_reason,'غير مناسب')),500)) on conflict(message_id,reporter_id) do nothing;
return jsonb_build_object('success',true); end; $$;
revoke all on function public.report_neighbor_message(bigint,text,bigint,text) from public;
grant execute on function public.report_neighbor_message(bigint,text,bigint,text) to anon,authenticated;
